# Generated by Django 4.2.2 on 2023-06-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Klass',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='klass',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='group',
            new_name='klass',
        ),
    ]
