# Generated by Django 4.2.2 on 2023-06-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_rename_group_klass_rename_group_student_klass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='klass',
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
