# Generated by Django 4.2.2 on 2023-06-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_remove_teacher_klass_klass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='fio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=255),
        ),
    ]
